# Global parameter defaults
path: /var/www/html/bellavista
url: http://localhost:8080/bellavista
user: bellavista
color: true
debug: false
disabled_commands:
  - db drop

config create:
    dbuser: fcjurado
    dbpass: mysql

core download:
    locale: es_ES

config create:
    dbname: bellavista
    dbuser: fcjurado
    dbpass: mysql

core install:
    title: Bellavista
    admin_user: bellavista
    admin_password: bellavista
    admin_email: bellavista@fcjurado.com

scaffold child-theme:
    parent_theme: zakra
    theme_name: zakra-child
    author: bellavista
    author_uri: bellavista.com 
    theme_uri: bellavista-theme.com
    activate: true
    enable-network: true
    force: true

term generate category:
    count: 100

post generate:
    count: 10
    format: ids
    post_status: publish
    post_content: true
    post_date: 2019-01-01

comment generate: 
    count: 20 