# Global parameter defaults
path: /var/www/html/macarena
url: http://localhost:8080/macarena
user: macarena
color: true
debug: false
disabled_commands:
  - db drop

config create:
    dbuser: fcjurado
    dbpass: mysql

core download:
    locale: es_ES

config create:
    dbname: macarena
    dbuser: fcjurado
    dbpass: mysql

core install:
    title: Macarena
    admin_user: macarena
    admin_password: macarena
    admin_email: macarena@fcjurado.com

scaffold child-theme:
    parent_theme: lyrical
    theme_name: lyrical-child
    author: Macarena
    author_uri: macarena.com 
    theme_uri: macarena-theme.com
    activate: true
    enable-network: true
    force: true

term generate category:
    count: 100

post generate:
    count: 10
    format: ids
    post_status: publish
    post_content: true
    post_date: 2019-01-01

comment generate: 
    count: 5 