# Global parameter defaults
path: /var/www/html/triana
url: http://localhost:8080/triana
user: triana
color: true
debug: false
disabled_commands:
  - db drop

config create:
    dbuser: fcjurado
    dbpass: mysql

core download:
    locale: es_ES

config create:
    dbname: triana
    dbuser: fcjurado
    dbpass: mysql

core install:
    title: Triana
    admin_user: triana
    admin_password: triana
    admin_email: triana@fcjurado.com

scaffold child-theme:
    parent_theme: astra
    theme_name: astra-child
    author: triana
    author_uri: triana.com 
    theme_uri: triana-theme.com
    activate: true
    enable-network: true
    force: true

term generate category:
    count: 100

post generate:
    count: 10
    format: ids
    post_status: publish
    post_content: true
    post_date: 2019-01-01

comment generate: 
    count: 15 

language plugin update:
    all: true

language theme update:
    all: true

search-replace:
    verbose: true

media regenerate:
    yes: true

transient delete:
    expired: true

profile stage:
     all: true
     spotlight: true
     allow-root: true